"""Compatibility facade for canonical kernel, runtime, and orchestration records.

Kernel contracts are owned by :mod:`daedalus.kernel.contracts`; provider
reports by :mod:`daedalus.runtimes.contracts.provider_report`; legacy agent
tasks and run projections by :mod:`daedalus.orchestration.legacy_reports`.
This module preserves existing imports with exact object identity and contains
no second implementation or mutable singleton state.
"""

from daedalus.kernel.contracts.canonical import (
    KERNEL_CONTRACT_TYPES,
    KERNEL_CONTRACT_VERSION,
    RUNTIME_CONFORMANCE_CHECKS,
    AttemptContract,
    AttemptReceipt,
    CampaignContract,
    CampaignReceipt,
    CampaignTrialReceipt,
    CanonicalContract,
    ConformanceCheck,
    ContractProvenance,
    EffectScope,
    EvidenceItem,
    EvidencePacket,
    ExperimentSpec,
    MissionContract,
    NominationReceipt,
    PolicyDecision,
    PromotionReceipt,
    ResourceBudget,
    ResourceUsage,
    RuntimeCapabilities,
    RuntimeConformanceReceipt,
    RuntimeManifest,
    _artifact_locator,
    _attempt_evidence_projection,
    _egress_endpoint,
    _freeze_json,
    _identifier,
    _json_value,
    _locator_sha256,
    _non_empty,
    _record_payload,
    _repo_path,
    _require_provenance_inputs,
    _revision,
    _sha256,
    _snapshot_execution_limit_policy,
    _sorted_strings,
    _utc_timestamp,
    derive_work_item_id,
    parse_kernel_contract,
    work_item_identity_sha256,
)
from daedalus.orchestration.legacy_reports import AgentTask, RunState
from daedalus.runtimes.contracts.provider_report import (
    REPORT_KEYS,
    AgentReport,
    validate_report,
)

__all__ = [
    "KERNEL_CONTRACT_VERSION",
    "RUNTIME_CONFORMANCE_CHECKS",
    "CanonicalContract",
    "ContractProvenance",
    "ResourceBudget",
    "ResourceUsage",
    "EffectScope",
    "RuntimeCapabilities",
    "MissionContract",
    "derive_work_item_id",
    "work_item_identity_sha256",
    "AttemptContract",
    "EvidenceItem",
    "EvidencePacket",
    "ExperimentSpec",
    "CampaignContract",
    "CampaignTrialReceipt",
    "CampaignReceipt",
    "PolicyDecision",
    "RuntimeManifest",
    "AttemptReceipt",
    "NominationReceipt",
    "PromotionReceipt",
    "ConformanceCheck",
    "RuntimeConformanceReceipt",
    "KERNEL_CONTRACT_TYPES",
    "parse_kernel_contract",
    "REPORT_KEYS",
    "AgentTask",
    "AgentReport",
    "RunState",
    "validate_report",
]
