"""Trust-kernel capabilities introduced through Gate-0 work packets.

Legacy modules remain import-compatible while new security boundaries are
added here incrementally. This package is not a second contract authority;
canonical wire contracts remain in :mod:`daedalus.schemas`.
"""

from .contracts import OwnerApproval
from .approvals import (
    ApprovalBindingMismatch,
    ApprovalConsumptionMismatch,
    ApprovalExpired,
    ConsumedOwnerApproval,
    ApprovalLedger,
    ApprovalReplay,
    ApprovalSignatureError,
    ApprovalExpectation,
    VerifiedOwnerApproval,
    issue_owner_approval,
    verify_owner_approval,
)

__all__ = [
    "ApprovalBindingMismatch",
    "ApprovalConsumptionMismatch",
    "ApprovalExpired",
    "ConsumedOwnerApproval",
    "ApprovalExpectation",
    "ApprovalLedger",
    "ApprovalReplay",
    "ApprovalSignatureError",
    "OwnerApproval",
    "VerifiedOwnerApproval",
    "issue_owner_approval",
    "verify_owner_approval",
]

from .contracts import (
    OFFLOAD_EXECUTION_EFFECTS,
    EffectLease,
    EffectLeaseRequest,
    OffloadExecutionPlan,
    OffloadExecutionPlanV1,
    OffloadExecutionPlanV2,
    OffloadExecutionPlanV3,
    decode_offload_execution_plan,
    derive_offload_recovery_path,
    derive_offload_staging_path,
    offload_recovery_path_sha256,
    offload_staging_path_sha256,
)
from .effects import (
    ClaimCompletionCapability,
    ClaimTerminalAuthorization,
    CompletionCapability,
    EffectExecutionClaim,
    EffectExecutionClaimReceipt,
    EffectExecutionRequest,
    EffectLeaseBindingMismatch,
    EffectLeaseConcurrencyError,
    EffectLeaseError,
    EffectLeaseExpired,
    EffectLeaseLedger,
    EffectLeaseReplay,
    EffectReconciliationRequired,
    EffectLeaseScopeError,
    EffectLeaseSignatureError,
    EffectLeaseStateError,
    EffectStartResult,
    EffectTerminalReceipt,
    LeasedEffectStartReceipt,
    LeasedEffectAuthorization,
    TerminalAuthorization,
    freeze_effect_terminal_receipt,
    issue_effect_lease,
    verify_effect_lease,
)
from .reconciliation import (
    EffectReconciliationBindingError,
    EffectReconciliationConflict,
    EffectReconciliationDecision,
    EffectReconciliationError,
    EffectReconciliationExpired,
    EffectReconciliationReplay,
    EffectReconciliationResult,
    EffectReconciliationSignatureError,
    issue_effect_reconciliation_decision,
    reconcile_effect_terminal,
    verify_effect_reconciliation_decision,
)
from .offload_authority import (
    AuthorizedOffloadExecution,
    OffloadAuthorityBindingError,
    authorize_offload_execution,
    derive_offload_execution_ids,
)
from .offload_observations import (
    BASE_SOURCE_ARTIFACT_KIND,
    OLLAMA_METADATA_ARTIFACT_KIND,
    SOURCE_FINGERPRINT_ARTIFACT_KIND,
    OffloadObservationError,
    OffloadWorkspaceObservation,
    OllamaChatObservation,
    OllamaChatObservationV1,
    OllamaModelObservation,
    OllamaModelObservationV1,
    TargetBeforeObservation,
    TargetBeforeObservationV1,
    TaskAttemptWorkspaceAttestation,
    decode_ollama_chat_observation,
    decode_ollama_model_observation,
)
from .runtime_tools import (
    RuntimeToolBinding,
    RuntimeToolBindingError,
    VerifiedRuntimeToolHandle,
)
from .resolved_kill_switch import (
    ResolvedKillSwitch,
    kill_switch_path_sha256,
    kill_switch_ref_for_path,
)

__all__ += [
    "ClaimCompletionCapability",
    "ClaimTerminalAuthorization",
    "CompletionCapability",
    "EffectExecutionClaim",
    "EffectExecutionClaimReceipt",
    "EffectExecutionRequest",
    "EffectLease",
    "EffectLeaseBindingMismatch",
    "EffectLeaseConcurrencyError",
    "EffectLeaseError",
    "EffectLeaseExpired",
    "EffectLeaseLedger",
    "EffectLeaseReplay",
    "EffectReconciliationRequired",
    "EffectLeaseRequest",
    "EffectLeaseScopeError",
    "EffectLeaseSignatureError",
    "EffectLeaseStateError",
    "EffectStartResult",
    "EffectTerminalReceipt",
    "LeasedEffectStartReceipt",
    "LeasedEffectAuthorization",
    "TerminalAuthorization",
    "freeze_effect_terminal_receipt",
    "OFFLOAD_EXECUTION_EFFECTS",
    "OffloadExecutionPlan",
    "OffloadExecutionPlanV1",
    "OffloadExecutionPlanV2",
    "OffloadExecutionPlanV3",
    "decode_offload_execution_plan",
    "derive_offload_recovery_path",
    "derive_offload_staging_path",
    "offload_recovery_path_sha256",
    "offload_staging_path_sha256",
    "issue_effect_lease",
    "verify_effect_lease",
    "AuthorizedOffloadExecution",
    "OffloadAuthorityBindingError",
    "authorize_offload_execution",
    "derive_offload_execution_ids",
    "BASE_SOURCE_ARTIFACT_KIND",
    "OLLAMA_METADATA_ARTIFACT_KIND",
    "SOURCE_FINGERPRINT_ARTIFACT_KIND",
    "OffloadObservationError",
    "OffloadWorkspaceObservation",
    "OllamaChatObservation",
    "OllamaChatObservationV1",
    "OllamaModelObservation",
    "OllamaModelObservationV1",
    "TargetBeforeObservation",
    "TargetBeforeObservationV1",
    "TaskAttemptWorkspaceAttestation",
    "decode_ollama_chat_observation",
    "decode_ollama_model_observation",
    "RuntimeToolBinding",
    "RuntimeToolBindingError",
    "VerifiedRuntimeToolHandle",
    "ResolvedKillSwitch",
    "kill_switch_path_sha256",
    "kill_switch_ref_for_path",
    "EffectReconciliationBindingError",
    "EffectReconciliationConflict",
    "EffectReconciliationDecision",
    "EffectReconciliationError",
    "EffectReconciliationExpired",
    "EffectReconciliationReplay",
    "EffectReconciliationResult",
    "EffectReconciliationSignatureError",
    "issue_effect_reconciliation_decision",
    "reconcile_effect_terminal",
    "verify_effect_reconciliation_decision",
]

from .fourfold_evidence import (
    FOURFOLD_EVIDENCE_SCHEMA,
    FOURFOLD_EVALUATOR,
    FourfoldEvidenceExpectation,
    FourfoldEvidenceMismatch,
    assemble_fourfold_evidence_packet,
    verify_fourfold_evidence_packet,
)

__all__ += [
    "FOURFOLD_EVIDENCE_SCHEMA",
    "FOURFOLD_EVALUATOR",
    "FourfoldEvidenceExpectation",
    "FourfoldEvidenceMismatch",
    "assemble_fourfold_evidence_packet",
    "verify_fourfold_evidence_packet",
]

from .promotion import (
    PromotionAuthorization,
    PromotionAuthorizationError,
    authorize_promotion,
    candidate_batch_sha256,
    resolve_live_target_revision,
)
from .runtime_conformance import (
    RecordedObservation,
    RuntimeConformanceError,
    assemble_recorded_conformance,
    verify_current_conformance,
)
from .sandbox import (
    DockerSandboxPolicy,
    SandboxExecutionReceipt,
    SandboxMount,
    SandboxPolicyError,
    run_in_docker_sandbox,
)

__all__ += [
    "PromotionAuthorization",
    "PromotionAuthorizationError",
    "authorize_promotion",
    "candidate_batch_sha256",
    "resolve_live_target_revision",
    "RecordedObservation",
    "RuntimeConformanceError",
    "assemble_recorded_conformance",
    "verify_current_conformance",
    "DockerSandboxPolicy",
    "SandboxExecutionReceipt",
    "SandboxMount",
    "SandboxPolicyError",
    "run_in_docker_sandbox",
]
