"""inventory -- the GENERATED feature census.

``docs/FEATURE_INVENTORY.json`` used to be typed by hand. It stamped the
revision it was written against and then sat there while thirty commits landed
on top of it, and because the self-improvement picker reads its two highest
bands, the thing that chooses what gets worked on next was reasoning about a
tree that no longer existed. The repo's own narrative records the size of that
failure mode: a hand-written inventory listed 136 features where a deep read of
the same tree found 827.

This module replaces the typing. It derives every mechanical field from the
same single walk of the tree that ``daedalus map`` already performs
(:func:`daedalus.mapping.render.analyse_once`), so the census cannot be older
than the run that produced it.

WHAT IS DERIVABLE, AND WHAT IS NOT
----------------------------------
Derivable, and therefore regenerated on every run:

  * the module census and its ``status`` -- wired / island / shim / unknown --
    straight off :func:`daedalus.mapping.reach.analyse`'s classification;
  * ``entrypoints``, ``entry_kinds``, ``importers`` and ``tests`` per module;
  * the CLI dispatch table and the HTTP route table, from the entry points;
  * every environment switch, where it is read, whether it is dark and whether
    any document mentions it, from :mod:`daedalus.mapping.switches`;
  * two kinds of ``stale``: a package this repo's own packaging metadata
    promises that is not on disk, and a ``__pycache__`` whose sources are gone;
  * the packaging gap in the other direction -- a package on disk that a wheel
    would not contain.

NOT derivable, and therefore preserved rather than invented:

  * ``notes`` -- WHY a thing is the way it is. No scanner derives that.
  * ``kind`` -- the semantic taxonomy (safety / orchestration / provider /
    memory). A path prefix is a hint, not a fact.
  * ``name`` -- the human-legible name of a capability, as opposed to the file
    it happens to live in.
  * ``status: planned`` and ``status: baseline`` -- a feature that has no code
    yet has no evidence a scanner can read, and "this is deliberately only a
    baseline" is a judgement.
  * every feature whose surface is not Python: the web app, the VS Code
    extension, the crew protocol files. The reachability engine walks ``.py``;
    claiming to have measured a ``.tsx`` would be a lie of scope.

THE MERGE
---------
Mechanical fields are rewritten every run. Human fields live in ``annotations``
(keyed to a module, an env var or a route) and ``narrative_features`` (whole
hand-written entries with no mechanical counterpart), and are merged into the
output for consumers -- but the ``digest`` is computed over a projection that
strips them again. So:

  * editing a note, a name or a kind is legal and does not trip the gate;
  * editing a ``status``, a test list or an island entry DOES trip it, because
    that is the half a human is not supposed to write.

That is a refinement of the rule :func:`daedalus.mapping.drift._digest` states
for the map snapshot, where the human half is a whole top-level block. Here the
human half is interleaved with the mechanical half by field, so the digest is
taken over a projection instead of over a key list.

Annotations carry human fields ONLY. An annotation cannot set ``status`` and
cannot add a module, because the failure being fixed is a hand-written file
steering the work queue -- handing that same power back through a side door
would be the same defect wearing a generated file's clothes.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

__all__ = [
    "AREA_HUMAN_FIELDS",
    "DIGEST_KEY",
    "ENV_HUMAN_FIELDS",
    "FEATURE_HUMAN_FIELDS",
    "INVENTORY_REL",
    "SCHEMA",
    "STATUS_BY_CLASS",
    "annotation_overreach",
    "build",
    "check",
    "digest_ok",
    "harvest",
    "inventory_bytes",
    "load",
    "main",
    "refresh",
    "write_inventory",
]

SCHEMA = "daedalus-feature-inventory/2"

INVENTORY_REL = "docs/FEATURE_INVENTORY.json"

DIGEST_KEY = "digest"

_NOTE = (
    "GENERATED by daedalus.mapping.inventory from the same walk of the tree "
    "that daedalus map performs. Hand-edit ONLY 'annotations', "
    "'narrative_features' and the per-record human fields they feed (name, "
    "kind, notes, purpose, title); every derived field is covered by 'digest'. "
    "Regenerate with: python -m daedalus.mapping.inventory --refresh"
)

# The fields a HUMAN owns on a generated record. They are merged into the
# output so a consumer reads one document, and stripped again before the digest
# so that writing them is not an integrity violation.
FEATURE_HUMAN_FIELDS = ("name", "kind", "notes")
ENV_HUMAN_FIELDS = ("purpose",)
AREA_HUMAN_FIELDS = ("title",)

# Top-level keys the digest never covers: the constant note, the human blocks,
# the digest itself, and the two fields whose value is a function of the human
# blocks (``unmatched_annotations``) or of a clock-adjacent probe that the
# picker explicitly refuses to treat as staleness (``repo_state.dirty``).
_HUMAN_TOP_KEYS = frozenset({
    "note", "annotations", "narrative_features", "unmatched_annotations",
    DIGEST_KEY,
})

# reach classification -> inventory status. ``orphan`` folds into ``island``:
# both mean "no entry point reaches it", and the map's own gate already merges
# them (drift.ISLAND_CLASSES). ``test`` modules are not features and are
# dropped entirely.
STATUS_BY_CLASS = {
    "entry": "wired",
    "reachable": "wired",
    "island": "island",
    "orphan": "island",
    "shim": "shim",
    "unknown": "unknown",
}

STATUS_ISLAND = "island"
STATUS_STALE = "stale"

# Where the mechanically-detected staleness is filed. A distinct area so a
# reader can tell "the tree contradicts this repo's own metadata" from "this
# module is unreachable", which want different verbs.
METADATA_AREA = "(repo metadata)"

# Directories a stale sweep must NOT descend into. Deliberately NOT the same
# set as reach._IGNORE_DIRS: ``build`` and ``__pycache__`` are excluded there
# precisely because they are not source, and they are exactly what this sweep
# is looking for.
_STALE_SKIP_DIRS = frozenset({
    ".git", ".hg", ".svn", "node_modules", ".venv", "venv", "env",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", ".idea", ".vs", ".vscode",
    "vendor", ".cache", "target", "dist", ".daedalus_worktrees",
})

# The HTTP method a route handler implies. web_api dispatches on the request
# method by putting it in the handler's name, so this is a reading of the
# evidence rather than a guess -- and a handler that does not follow the
# convention yields "" rather than a fabricated method.
_METHOD_BY_SUFFIX = (
    ("_handle_delete", "DELETE"), ("_handle_patch", "PATCH"),
    ("_handle_post", "POST"), ("_handle_put", "PUT"), ("_handle_get", "GET"),
)

# Tokens inside a hand-written entrypoint string that could name a module.
# Starts at a letter or underscore so "/api/x" and ".claude/y" do not produce a
# phantom leading-punctuation token.
_TOKEN_RE = re.compile(r"[A-Za-z_][\w./\\-]*")

_SCRIPTS_HEADER = re.compile(r"^\s*\[tool\.setuptools\]\s*$")
_SECTION_RE = re.compile(r"^\s*\[")
_PACKAGES_RE = re.compile(r"^\s*packages\s*=\s*(.*)$")
_QUOTED_RE = re.compile(r"[\"']([^\"']+)[\"']")


# --------------------------------------------------------------------------
# digest
# --------------------------------------------------------------------------

def _strip_human(doc: Mapping[str, Any]) -> dict:
    """The mechanical projection of a whole document.

    Everything a human is allowed to write is removed: the human top-level
    blocks, and the human FIELDS interleaved into the generated records. What
    is left is exactly what this module derives, which is exactly what a digest
    should be a function of.
    """
    body: dict[str, Any] = {}
    for key, value in doc.items():
        if key in _HUMAN_TOP_KEYS:
            continue
        if key == "areas":
            areas = []
            for area in value or []:
                if not isinstance(area, Mapping):
                    continue
                features = []
                for feat in area.get("features") or []:
                    if not isinstance(feat, Mapping):
                        continue
                    features.append({k: v for k, v in feat.items()
                                     if k not in FEATURE_HUMAN_FIELDS})
                areas.append({
                    **{k: v for k, v in area.items()
                       if k not in AREA_HUMAN_FIELDS and k != "features"},
                    "features": features,
                })
            body[key] = areas
        elif key == "env_vars":
            body[key] = [{k: v for k, v in row.items()
                          if k not in ENV_HUMAN_FIELDS}
                         for row in value or [] if isinstance(row, Mapping)]
        elif key == "repo_state":
            # The revision, and only the revision. ``branch`` and ``dirty``
            # move without the architecture moving, and a gate that goes red
            # because somebody has unsaved edits is a gate people switch off.
            state = value if isinstance(value, Mapping) else {}
            body[key] = {"head": state.get("head")}
        else:
            body[key] = value
    return body


def _digest(doc: Mapping[str, Any]) -> str:
    """A hash over the derived half only. Canonical JSON, sorted keys, so the
    value is a function of the content and not of the writer's key order."""
    blob = json.dumps(_strip_human(doc), sort_keys=True, ensure_ascii=False,
                      separators=(",", ":"))
    return "sha256:" + hashlib.sha256(blob.encode("utf-8")).hexdigest()


def digest_ok(doc: Any) -> bool:
    """Does this document's own digest still cover its own derived fields?

    Public for the same reason :func:`daedalus.mapping.drift.digest_ok` is: any
    consumer that RANKS WORK out of these lists rather than rescanning has to
    ask this first. Ranking work out of a hand-edited census is precisely the
    defect this module was written to end.
    """
    if not isinstance(doc, Mapping) or doc.get("__error__"):
        return False
    return doc.get(DIGEST_KEY) == _digest(doc)


# --------------------------------------------------------------------------
# small derivations
# --------------------------------------------------------------------------

def _area_of(rel: str) -> str:
    parent = rel.rsplit("/", 1)[0] if "/" in rel else ""
    return parent or "(repo root)"


def _dotted(rel: str) -> str:
    stem = rel[:-3] if rel.endswith(".py") else rel
    if stem.endswith("/__init__"):
        stem = stem[: -len("/__init__")]
    return stem.replace("/", ".")


def _method_of(function: str) -> str:
    for suffix, method in _METHOD_BY_SUFFIX:
        if function.endswith(suffix):
            return method
    return ""


def _pyproject_packages(root: Path) -> list[str]:
    """The explicit ``[tool.setuptools] packages`` list, or ``[]``.

    A line scanner rather than a TOML parser: this module is stdlib-only across
    3.10 (no ``tomllib``), and the shape being read is one array under one
    known table. An unreadable or absent pyproject yields an empty list, which
    both detectors below read as "no promise was made" -- never as a finding.
    """
    path = root / "pyproject.toml"
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []
    out: list[str] = []
    in_table = False
    in_array = False
    for line in text.splitlines():
        if in_array:
            out.extend(_QUOTED_RE.findall(line))
            if "]" in line:
                in_array = False
                break
            continue
        if _SCRIPTS_HEADER.match(line):
            in_table = True
            continue
        if in_table and _SECTION_RE.match(line):
            break
        if not in_table:
            continue
        m = _PACKAGES_RE.match(line)
        if not m:
            continue
        rest = m.group(1)
        out.extend(_QUOTED_RE.findall(rest))
        if "]" not in rest:
            in_array = True
    return sorted(set(out))


def _packages_on_disk(root: Path, listed: Sequence[str]) -> list[str]:
    """Dotted packages that exist under the distribution roots the metadata
    already names. Scoped to those roots on purpose: every directory in the
    repo with an ``__init__.py`` is not a candidate for the wheel, and treating
    a fixture or a runs/ directory as one would manufacture findings."""
    roots = sorted({name.split(".", 1)[0] for name in listed})
    found: list[str] = []
    for top in roots:
        base = root / top
        if not base.is_dir():
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = sorted(d for d in dirnames
                                 if d not in _STALE_SKIP_DIRS
                                 and not d.startswith("."))
            if "__init__.py" not in filenames:
                continue
            rel = Path(dirpath).relative_to(root).as_posix()
            found.append(rel.replace("/", "."))
    return sorted(set(found))


def _orphan_bytecode(root: Path) -> list[tuple[str, int]]:
    """``__pycache__`` directories holding bytecode whose sources are gone.

    The exact shape of the ``daedalus/hermes`` remnant the hand-written
    inventory recorded: the package was deleted, the ``.pyc`` files stayed, and
    an import of the dotted name could still resolve. A cache beside live
    sources is not a finding -- only one with NO sibling ``.py`` at all.
    """
    out: list[tuple[str, int]] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in _STALE_SKIP_DIRS)
        if Path(dirpath).name != "__pycache__":
            continue
        pyc = [f for f in filenames if f.endswith(".pyc")]
        if not pyc:
            continue
        parent = Path(dirpath).parent
        try:
            siblings = [f for f in os.listdir(parent) if f.endswith(".py")]
        except OSError:
            continue
        if siblings:
            continue
        out.append((Path(dirpath).relative_to(root).as_posix(), len(pyc)))
    return sorted(out)


# --------------------------------------------------------------------------
# the human half
# --------------------------------------------------------------------------

def _clean_annotation(raw: Any, allowed: Sequence[str]) -> dict:
    if not isinstance(raw, Mapping):
        return {}
    out = {}
    for key in allowed:
        value = raw.get(key)
        if isinstance(value, str) and value.strip():
            out[key] = value.strip()
    return out


def annotation_overreach(annotations: Mapping[str, Any]) -> list[str]:
    """Annotation keys carrying fields a human is NOT allowed to set.

    Reported rather than silently dropped. Silently dropping is how a person
    concludes the field works; naming it is how they learn the rule. The build
    ignores these fields either way -- an annotation that could set ``status``
    would hand the hand-written file's exact power back through a side door.
    """
    allowed = set(FEATURE_HUMAN_FIELDS) | set(ENV_HUMAN_FIELDS) | set(AREA_HUMAN_FIELDS)
    bad: list[str] = []
    for key, value in sorted((annotations or {}).items()):
        if not isinstance(value, Mapping):
            bad.append(f"{key}: not an object")
            continue
        extra = sorted(set(value) - allowed)
        if extra:
            bad.append(f"{key}: {', '.join(extra)}")
    return bad


def _module_targets(feature: Mapping[str, Any], known: Iterable[str]) -> list[str]:
    """Every module a hand-written feature's entrypoints resolve to.

    ALL of them, not the first: the kairos-rename shim entry names five modules
    in one feature, and attaching its rationale to only one of them would lose
    the reason for the other four.
    """
    known_set = set(known)
    hits: list[str] = []
    raw = feature.get("entrypoints")
    if isinstance(raw, str):
        raw = [raw]
    for entry in raw or []:
        for token in _TOKEN_RE.findall(str(entry)):
            cand = token.replace("\\", "/")
            if cand.endswith(".py"):
                if cand in known_set and cand not in hits:
                    hits.append(cand)
                continue
            if "/" in cand or "." not in cand:
                continue
            stem = cand.replace(".", "/")
            for rel in (stem + ".py", stem + "/__init__.py"):
                if rel in known_set and rel not in hits:
                    hits.append(rel)
    return hits


def harvest(old: Mapping[str, Any], modules: Sequence[str],
            env_names: Sequence[str] = ()) -> tuple[dict, list, dict]:
    """Lift the human half out of a previous inventory. LOSSLESS by contract.

    Returns ``(annotations, narrative_features, stats)``. Every feature in the
    old document ends up in exactly one of the two: an annotation keyed to the
    module(s) its entrypoints name, or a verbatim narrative feature. Nothing is
    dropped, because a generated file that discards the rationale somebody
    wrote is not progress -- it is the same rot with a fresher timestamp.

    Already-schema-2 documents pass their blocks straight through; the harvest
    only has work to do the first time.
    """
    annotations: dict[str, dict] = {}
    narrative: list[dict] = []
    stats = {"old_features": 0, "matched": 0, "narrative": 0, "env": 0}

    if not isinstance(old, Mapping) or not old:
        return annotations, narrative, stats

    if old.get("schema") == SCHEMA:
        raw_ann = old.get("annotations")
        if isinstance(raw_ann, Mapping):
            for key, value in raw_ann.items():
                cleaned = _clean_annotation(
                    value, FEATURE_HUMAN_FIELDS + ENV_HUMAN_FIELDS
                    + AREA_HUMAN_FIELDS)
                if cleaned:
                    annotations[str(key)] = cleaned
        raw_narr = old.get("narrative_features")
        if isinstance(raw_narr, (list, tuple)):
            narrative = [dict(f) for f in raw_narr if isinstance(f, Mapping)]
        stats["matched"] = len(annotations)
        stats["narrative"] = len(narrative)
        return annotations, narrative, stats

    known = set(modules)
    for area in old.get("areas") or []:
        if not isinstance(area, Mapping):
            continue
        area_name = str(area.get("area") or "")
        for feature in area.get("features") or []:
            if not isinstance(feature, Mapping):
                continue
            stats["old_features"] += 1
            targets = _module_targets(feature, known)
            human = {}
            for field_name in FEATURE_HUMAN_FIELDS:
                value = feature.get(field_name)
                if isinstance(value, str) and value.strip():
                    human[field_name] = value.strip()
            if not targets:
                entry = dict(feature)
                entry["area"] = area_name
                narrative.append(entry)
                stats["narrative"] += 1
                continue
            stats["matched"] += 1
            for rel in targets:
                key = "module:" + rel
                existing = annotations.get(key)
                if existing is None:
                    annotations[key] = dict(human)
                    continue
                # Two hand-written features naming one module. Both reasons are
                # kept, joined, rather than one silently winning.
                for field_name, value in human.items():
                    prior = existing.get(field_name, "")
                    if not prior:
                        existing[field_name] = value
                    elif value not in prior:
                        existing[field_name] = f"{prior} | {value}"

    env_known = set(env_names)
    for row in old.get("env_vars") or []:
        if not isinstance(row, Mapping):
            continue
        name = str(row.get("name") or "").strip()
        purpose = str(row.get("purpose") or "").strip()
        if not name or not purpose:
            continue
        stats["env"] += 1
        key = "env:" + name
        if name in env_known or key not in annotations:
            annotations.setdefault(key, {})["purpose"] = purpose

    return annotations, narrative, stats


# --------------------------------------------------------------------------
# the build
# --------------------------------------------------------------------------

def _feature(rel: str, facts, entry_idents: Sequence[str],
             dark_by_module: Mapping[str, Sequence[str]],
             annotation: Mapping[str, str]) -> dict:
    status = STATUS_BY_CLASS.get(facts.classification, facts.classification)
    out = {
        "module": rel,
        "status": status,
        "classification": facts.classification,
        "reason": facts.reason,
        "entry_kinds": sorted({i.split(":", 1)[0] for i in entry_idents}),
        "entrypoints": list(entry_idents),
        "reached_from": facts.entry,
        "tests": list(facts.tested_by),
        "importers": list(facts.imported_by),
        "dark_switches": list(dark_by_module.get(rel, ())),
        # human, merged for the reader, stripped before the digest
        "name": annotation.get("name") or rel,
        "kind": annotation.get("kind") or "",
        "notes": annotation.get("notes") or "",
    }
    return out


def _stale_features(root: Path, annotations: Mapping[str, Mapping[str, str]]
                    ) -> tuple[list[dict], dict]:
    """The two mechanically-detectable kinds of staleness, plus the packaging
    picture they come from.

    Deliberately only two. "This directory is a superseded experiment" and
    "this mockup was replaced by the shipped app" are judgements about intent,
    and a scanner that guessed at them would fill the work queue with its own
    guesses. They stay in ``narrative_features``, where a human signed them.
    """
    listed = _pyproject_packages(root)
    on_disk = _packages_on_disk(root, listed)
    ghosts = [p for p in listed if p not in set(on_disk)]
    gaps = [p for p in on_disk if p not in set(listed)]
    orphans = _orphan_bytecode(root)

    features: list[dict] = []
    for pkg in ghosts:
        key = "stale:package:" + pkg
        ann = annotations.get(key, {})
        features.append({
            "module": "",
            "status": STATUS_STALE,
            "detector": "packaging_ghost",
            "reason": (f"pyproject.toml [tool.setuptools] packages promises "
                       f"{pkg!r}, and no directory with an __init__.py answers "
                       f"to that name -- a non-editable install would ship a "
                       f"package that is not there"),
            "entrypoints": ["pyproject.toml [tool.setuptools] packages"],
            "tests": [],
            "name": ann.get("name") or f"packaging ghost: {pkg}",
            "kind": ann.get("kind") or "",
            "notes": ann.get("notes") or "",
        })
    for rel, count in orphans:
        key = "stale:bytecode:" + rel
        ann = annotations.get(key, {})
        features.append({
            "module": "",
            "status": STATUS_STALE,
            "detector": "orphan_bytecode",
            "reason": (f"{rel} holds {count} .pyc file(s) and its parent "
                       f"directory contains no .py source at all -- the module "
                       f"was deleted and its bytecode was not"),
            "entrypoints": [rel],
            "tests": [],
            "name": ann.get("name") or f"orphan bytecode: {rel}",
            "kind": ann.get("kind") or "",
            "notes": ann.get("notes") or "",
        })

    packaging = {
        "listed": listed,
        "on_disk": on_disk,
        # Reported, NOT filed as a stale feature. Its remedy is "add it to the
        # list", the exact opposite verb from the stale remedy ("remove it"),
        # and handing a fixer the wrong verb is how a finding becomes damage.
        "on_disk_but_unlisted": gaps,
        "listed_but_absent": ghosts,
    }
    return features, packaging


def build(repo_root, *, index=None, reports=None, annotations=None,
          narrative_features=None, probe_dirty: bool = True,
          head: str | None = None, branch: str | None = None,
          dirty: bool | None = None) -> dict:
    """Derive the whole document. Writes nothing.

    ``reports`` is the ``(reach, switches)`` pair from
    :func:`daedalus.mapping.render.analyse_once`. When it is not supplied this
    calls that function -- which is the configuration the PRODUCT uses, index
    and all. Calling ``reach.analyse(root)`` with no index here would be a
    second engine configuration that ships to nobody, and the last time a guard
    did that a CRITICAL survived underneath it.
    """
    from . import render as render_mod

    root = Path(repo_root).resolve()
    reach_report, switch_report = reports or render_mod.analyse_once(root, index)

    annotations = dict(annotations or {})
    narrative_features = [dict(f) for f in (narrative_features or [])]

    # ---- entry points ----------------------------------------------------
    by_module: dict[str, list[str]] = {}
    for entry in reach_report.entry_points:
        by_module.setdefault(entry.module, []).append(entry.ident)
    for idents in by_module.values():
        idents.sort()

    script_modules = {e.module for e in reach_report.entry_points
                      if e.kind == "script"}
    invocations: list[str] = []
    for entry in reach_report.entry_points:
        if entry.kind == "script":
            invocations.append(entry.name)
        elif entry.kind in ("module_main", "main_guard"):
            invocations.append(f"python -m {_dotted(entry.module)}")
    invocations = sorted(set(invocations))

    cli_commands = [
        {"ident": e.ident, "literal": e.name, "module": e.module,
         "function": e.function, "console_script": e.module in script_modules,
         "targets": list(e.targets)}
        for e in sorted(reach_report.entry_points, key=lambda x: x.ident)
        if e.kind == "cli"
    ]
    api_endpoints = [
        {"route": e.name, "method": _method_of(e.function), "module": e.module,
         "function": e.function, "targets": list(e.targets)}
        for e in sorted(reach_report.entry_points, key=lambda x: (x.name, x.function))
        if e.kind == "http"
    ]
    bus_loops = [
        {"ident": e.ident, "module": e.module, "function": e.function}
        for e in sorted(reach_report.entry_points, key=lambda x: x.ident)
        if e.kind == "bus"
    ]

    # ---- env switches ----------------------------------------------------
    dark_by_module: dict[str, list[str]] = {}
    env_vars: list[dict] = []
    for switch in sorted(switch_report.env_switches, key=lambda s: s.name):
        read_in = sorted({site.module for site in switch.sites})
        if switch.dark:
            for module in read_in:
                dark_by_module.setdefault(module, []).append(switch.name)
        ann = annotations.get("env:" + switch.name, {})
        env_vars.append({
            "name": switch.name,
            "read_in": read_in,
            "kind": switch.kind,
            "state": switch.state,
            "default": switch.default,
            "dark": bool(switch.dark),
            "documented": bool(switch.documented),
            "purpose": ann.get("purpose") or "",
        })
    for names in dark_by_module.values():
        names.sort()

    # ---- the module census ----------------------------------------------
    grouped: dict[str, list[dict]] = {}
    status_counts: dict[str, int] = {}
    islands: list[str] = []
    shims: list[str] = []
    unknown: list[str] = []
    for facts in sorted(reach_report.modules, key=lambda m: m.module):
        if facts.classification == "test":
            continue
        rel = facts.module
        ann = annotations.get("module:" + rel, {})
        feature = _feature(rel, facts, by_module.get(rel, ()), dark_by_module, ann)
        grouped.setdefault(_area_of(rel), []).append(feature)
        status_counts[feature["status"]] = status_counts.get(feature["status"], 0) + 1
        if feature["status"] == STATUS_ISLAND:
            islands.append(rel)
        elif feature["status"] == "shim":
            shims.append(rel)
        elif feature["status"] == "unknown":
            unknown.append(rel)

    stale_features, packaging = _stale_features(root, annotations)
    if stale_features:
        grouped[METADATA_AREA] = stale_features
        status_counts[STATUS_STALE] = len(stale_features)

    areas = []
    for name in sorted(grouped):
        ann = annotations.get("area:" + name, {})
        areas.append({
            "area": name,
            "path": name,
            "title": ann.get("title") or "",
            "features": grouped[name],
        })

    # ---- the human blocks that matched nothing ---------------------------
    live_keys = ({"module:" + f["module"] for fs in grouped.values() for f in fs
                  if f.get("module")}
                 | {"env:" + row["name"] for row in env_vars}
                 | {"area:" + a["area"] for a in areas}
                 | {"stale:" + str(f.get("detector") or "") + ":" + str(f.get("name") or "")
                    for f in stale_features})
    unmatched = sorted(k for k in annotations
                       if k not in live_keys and not k.startswith("stale:"))

    if head is None or branch is None or dirty is None:
        stamp = render_mod.git_stamp(root, probe_dirty=probe_dirty)
        head = stamp.revision if head is None else head
        branch = stamp.branch if branch is None else branch
        if dirty is None:
            dirty = (True if stamp.dirty == "dirty"
                     else False if stamp.dirty == "clean" else None)

    doc: dict[str, Any] = {
        "schema": SCHEMA,
        "note": _NOTE,
        "repo_state": {"branch": branch, "head": head, "dirty": dirty},
        "counts": {
            "modules": sum(len(a["features"]) for a in areas),
            "areas": len(areas),
            **{f"status_{k}": v for k, v in sorted(status_counts.items())},
            "entry_points": len(reach_report.entry_points),
            "cli_commands": len(cli_commands),
            "api_endpoints": len(api_endpoints),
            "bus_loops": len(bus_loops),
            "invocations": len(invocations),
            "env_vars": len(env_vars),
            "dark_env_vars": sum(1 for row in env_vars if row["dark"]),
            "islands": len(islands),
            "shims": len(shims),
            "unknown": len(unknown),
            # The count that cannot be lowered by deleting a test.
            "unreached": len(set(islands) | set(shims) | set(unknown)),
            "stale": len(stale_features),
            "packaging_gaps": len(packaging["on_disk_but_unlisted"]),
            "narrative_features": len(narrative_features),
            "annotations": len(annotations),
        },
        "areas": areas,
        "invocations": invocations,
        "cli_commands": cli_commands,
        "api_endpoints": api_endpoints,
        "bus_loops": bus_loops,
        "env_vars": env_vars,
        "packaging": packaging,
        "unparsable": list(reach_report.unparsable),
        "broken_entries": list(reach_report.broken_entries),
        # The prose summaries the previous schema carried. Derived from the
        # SAME pass as the structured features, so the discrepancy the picker
        # reports when the two disagree cannot occur by construction.
        #
        # ``unreached`` is here because the island COUNT is gameable and was
        # demonstrated to be: "island" means unreachable but imported by a
        # test, so deleting the test moves the module to ``unknown`` and the
        # island count goes DOWN while the dead code stays. The union is the
        # number that cannot be improved by deleting a test, and the set diff
        # against the previous run is the honest signal -- not the count.
        "islands": islands,
        "shims": shims,
        "unknown": unknown,
        "unreached": sorted(set(islands) | set(shims) | set(unknown)),
        "stale": [f["reason"] for f in stale_features],
        # human half
        "annotations": {k: annotations[k] for k in sorted(annotations)},
        "narrative_features": narrative_features,
        "unmatched_annotations": unmatched,
    }
    doc[DIGEST_KEY] = _digest(doc)
    return doc


# --------------------------------------------------------------------------
# i/o
# --------------------------------------------------------------------------

def inventory_bytes(doc: Mapping[str, Any]) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def load(path) -> dict | None:
    p = Path(path)
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return {"__error__": str(exc)}


def write_inventory(path, doc: Mapping[str, Any]) -> str:
    text = inventory_bytes(doc)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8", newline="\n")
    return text


def refresh(repo_root, path=None, *, index=None, reports=None,
            probe_dirty: bool = True) -> dict:
    """Regenerate in place, carrying the human half forward.

    The old document is read for its annotations BEFORE it is overwritten, and
    a first run over a schema-1 file harvests them out of the hand-written
    entries. Refreshing is never a way to quietly drop somebody's stated
    reason.
    """
    root = Path(repo_root).resolve()
    target = Path(path) if path else root / INVENTORY_REL
    old = load(target) or {}
    if old.get("__error__"):
        old = {}

    from . import render as render_mod

    reports = reports or render_mod.analyse_once(root, index)
    reach_report, switch_report = reports
    modules = [m.module for m in reach_report.modules]
    env_names = [s.name for s in switch_report.env_switches]
    annotations, narrative, stats = harvest(old, modules, env_names)

    doc = build(root, reports=reports, annotations=annotations,
                narrative_features=narrative, probe_dirty=probe_dirty)
    write_inventory(target, doc)
    return {"path": str(target), "doc": doc, "harvest": stats}


def check(repo_root, path=None, *, index=None, reports=None,
          probe_dirty: bool = True) -> dict:
    """Gate mode. Writes nothing; returns ``{"ok": bool, "problems": [...]}``.

    Four ways to fail, in the order a reader needs them:
      1. there is no inventory, or it cannot be parsed;
      2. it was written by a different schema;
      3. its digest does not cover its own derived fields -- somebody edited
         the mechanical half by hand;
      4. regenerating it now would change something -- it is STALE, and the
         diff says exactly how.
    """
    root = Path(repo_root).resolve()
    target = Path(path) if path else root / INVENTORY_REL
    problems: list[str] = []

    stored = load(target)
    if stored is None:
        return {"ok": False, "path": str(target), "problems": [
            f"no inventory at {target}: nothing generated it. Run "
            f"`python -m daedalus.mapping.inventory --refresh`"]}
    if stored.get("__error__"):
        return {"ok": False, "path": str(target), "problems": [
            f"{target} could not be parsed: {stored['__error__']}"]}
    if stored.get("schema") != SCHEMA:
        return {"ok": False, "path": str(target), "problems": [
            f"{target} carries schema {stored.get('schema')!r}; this build "
            f"generates and compares {SCHEMA!r}"]}
    if not digest_ok(stored):
        problems.append(
            "the derived fields do not match the digest written with them: "
            "something was hand-edited. Pre-seeding a status, an island or a "
            "test list is not a way to steer the work queue")

    over = annotation_overreach(stored.get("annotations") or {})
    for entry in over:
        problems.append(f"annotation carries fields a human may not set -- {entry}")

    from . import render as render_mod

    reports = reports or render_mod.analyse_once(root, index)
    fresh = build(root, reports=reports,
                  annotations=stored.get("annotations") or {},
                  narrative_features=stored.get("narrative_features") or [],
                  probe_dirty=probe_dirty)

    old_body = _strip_human(stored)
    new_body = _strip_human(fresh)
    if old_body != new_body:
        problems.extend(_describe_drift(stored, fresh))

    return {"ok": not problems, "path": str(target), "problems": problems,
            "stored": stored, "fresh": fresh}


def _by_key(doc: Mapping[str, Any]) -> dict[str, dict]:
    """Every feature's DERIVED half, keyed by module (or by detector for the
    module-less stale entries). The human fields are dropped so a note cannot
    read as drift."""
    out: dict[str, dict] = {}
    for area in doc.get("areas") or []:
        for feat in (area or {}).get("features") or []:
            key = feat.get("module") or f"{feat.get('detector')}:{feat.get('reason')}"
            out[str(key)] = {k: v for k, v in feat.items()
                             if k not in FEATURE_HUMAN_FIELDS}
    return out


def _statuses(doc: Mapping[str, Any]) -> dict[str, str]:
    return {k: str(v.get("status")) for k, v in _by_key(doc).items()}


def _describe_drift(stored: Mapping[str, Any], fresh: Mapping[str, Any]) -> list[str]:
    out: list[str] = []
    old_head = (stored.get("repo_state") or {}).get("head")
    new_head = (fresh.get("repo_state") or {}).get("head")
    if old_head != new_head:
        out.append(f"written against {str(old_head)[:12]}; HEAD is "
                   f"{str(new_head)[:12]}")
    old_status = _statuses(stored)
    new_status = _statuses(fresh)
    for key in sorted(set(new_status) - set(old_status)):
        out.append(f"new feature {key} ({new_status[key]})")
    for key in sorted(set(old_status) - set(new_status)):
        out.append(f"feature gone: {key} (was {old_status[key]})")
    for key in sorted(set(old_status) & set(new_status)):
        if old_status[key] != new_status[key]:
            out.append(f"{key}: {old_status[key]} -> {new_status[key]}")
    for block in ("env_vars", "cli_commands", "api_endpoints", "invocations",
                  "bus_loops", "packaging"):
        if (stored.get(block) or []) != (fresh.get(block) or []):
            out.append(f"{block} moved")
    # Field-level, not just status-level. A module whose importers or reaching
    # entry point changed is a real difference, and reporting it as "something
    # differs, go diff the file yourself" is how a gate stops being read.
    old_feats, new_feats = _by_key(stored), _by_key(fresh)
    moved: list[str] = []
    for key in sorted(set(old_feats) & set(new_feats)):
        old_f, new_f = old_feats[key], new_feats[key]
        if old_f == new_f:
            continue
        fields = sorted(k for k in set(old_f) | set(new_f)
                        if old_f.get(k) != new_f.get(k) and k != "status")
        if fields:
            moved.append(f"{key}: {', '.join(fields)} changed")
    out.extend(moved[:10])
    if len(moved) > 10:
        out.append(f"... and {len(moved) - 10} more modules whose derived "
                   f"fields changed")
    if not out:
        out.append("the derived half differs from a fresh scan (no headline "
                   "difference; compare the file with --json)")
    return out


def render_text(doc: Mapping[str, Any]) -> str:
    counts = doc.get("counts") or {}
    state = doc.get("repo_state") or {}
    lines = [
        f"feature inventory: {SCHEMA}",
        f"  rev {str(state.get('head') or 'unknown')[:12]} on "
        f"{state.get('branch')} - dirty={state.get('dirty')}",
        "  modules=%s  wired=%s island=%s shim=%s unknown=%s stale=%s" % (
            counts.get("modules", 0), counts.get("status_wired", 0),
            counts.get("status_island", 0), counts.get("status_shim", 0),
            counts.get("status_unknown", 0), counts.get("status_stale", 0)),
        "  cli=%s api=%s bus=%s env=%s (dark %s)  packaging_gaps=%s" % (
            counts.get("cli_commands", 0), counts.get("api_endpoints", 0),
            counts.get("bus_loops", 0), counts.get("env_vars", 0),
            counts.get("dark_env_vars", 0), counts.get("packaging_gaps", 0)),
        "  human: %s annotations, %s narrative features, %s unmatched" % (
            counts.get("annotations", 0), counts.get("narrative_features", 0),
            len(doc.get("unmatched_annotations") or [])),
    ]
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="python -m daedalus.mapping.inventory",
        description="Generate docs/FEATURE_INVENTORY.json from the live tree. "
                    "Mechanical fields are rewritten every run; human notes are "
                    "carried forward and excluded from the digest.")
    ap.add_argument("--repo", default=".")
    ap.add_argument("--out", default=None, help=f"default {INVENTORY_REL}")
    ap.add_argument("--refresh", action="store_true",
                    help="regenerate the file in place")
    ap.add_argument("--check", action="store_true",
                    help="gate mode: exit non-zero if the file is missing, "
                         "hand-edited or stale; writes nothing")
    ap.add_argument("--json", action="store_true",
                    help="print the generated document; writes nothing")
    ap.add_argument("--no-git", action="store_true",
                    help="skip the working-tree dirty probe")
    args = ap.parse_args(list(argv) if argv is not None else None)

    root = Path(args.repo).resolve()
    target = Path(args.out) if args.out else root / INVENTORY_REL
    probe = not args.no_git

    if args.check:
        report = check(root, target, probe_dirty=probe)
        if report["ok"]:
            print(f"inventory: OK -- {report['path']} matches a fresh scan")
            return 0
        print(f"inventory: STALE or INVALID -- {report['path']}")
        for problem in report["problems"]:
            print(f"  - {problem}")
        print("\nRegenerate with `python -m daedalus.mapping.inventory "
              "--refresh` (or `daedalus map`, which does it as part of the run).")
        return 1

    if args.json:
        old = load(target) or {}
        from . import render as render_mod

        reports = render_mod.analyse_once(root)
        modules = [m.module for m in reports[0].modules]
        env_names = [s.name for s in reports[1].env_switches]
        annotations, narrative, _ = harvest(old, modules, env_names)
        doc = build(root, reports=reports, annotations=annotations,
                    narrative_features=narrative, probe_dirty=probe)
        print(json.dumps(doc, indent=2, ensure_ascii=False))
        return 0

    if not args.refresh:
        ap.error("nothing to do: pass --refresh, --check or --json")

    result = refresh(root, target, probe_dirty=probe)
    print(render_text(result["doc"]))
    stats = result["harvest"]
    if stats.get("old_features"):
        print(f"  harvested {stats['matched']} annotated + "
              f"{stats['narrative']} narrative from {stats['old_features']} "
              f"hand-written features, {stats['env']} env purposes")
    print(f"  wrote {result['path']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
